### ISSUE TITLE
journalspace: support for non-common prefix

### ISSUE THREAD

**Issue by pintohutch** [LiveRamp/gazette#134]
This is a request to support creating a set of journals without a common prefix. For example, given my journal spec yaml:
```
name: # not specified intentionally as there is no common prefix for these journals.
fragment:
  stores:
    - "s3://my-journals"
children:
  - name: foo-topic/
    children:
    - name: foo-topic/fragments/
       labels:
         - name: framing
         - value: json
         - name: topic
         - value: "foo-topic"
       children:
         - name: foo-topic/fragments/part-000
         - name: foo-topic/fragments/part-001
  - name: bar-topic/
    children:
    - name: bar-topic/fragments/
       labels:
         - name: framing
         - value: fixed
         - name: topic
         - value: "bar-topic"
       children:
         - name: bar-topic/fragments/part-000
         - name: bar-topic/fragments/part-001     
```
The resolved location in cloud storage for the four journals would be:
```
s3://my-journals/foo-topic/fragments/part-000
s3://my-journals/foo-topic/fragments/part-001
s3://my-journals/bar-topic/fragments/part-000
s3://my-journals/bar-topic/fragments/part-001
```
while the journal names themselves would be:
```
foo-topic/fragments/part-000
foo-topic/fragments/part-001
bar-topic/fragments/part-000
bar-topic/fragments/part-001
```

However, this currently is not supported, as `gazctl journals apply --dry-run` returns a
```
panic: runtime error: index out of range
```
when validating the yaml.
